sonar.organization=ChristianDDinga
sonar.projectKey=ChristianDDinga_demoses_grid_tariffs
sonar.host.url=https://sonarcloud.io
sonar.sources=src/demoses_grid_tariffs/
sonar.tests=tests/
sonar.links.homepage=https://github.com/ChristianDDinga/demoses_grid_tariffs
sonar.links.scm=git@github.com:ChristianDDinga/demoses_grid_tariffs
sonar.links.issue=https://github.com/ChristianDDinga/demoses_grid_tariffs/issues
sonar.links.ci=https://github.com/ChristianDDinga/demoses_grid_tariffs/actions
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-result.xml
sonar.python.pylint.reportPaths=pylint-report.txt
